email: me@barnden.dev
description: >-
  Brandon G. Nguyen's personal website
baseurl: "/"
permalink: /:year/:month/:title
url: "https://barnden.dev"
linkedin_username: brandon-g-nguyen
github_username:  barnden
date_format: "%Y %b %-d"
title: "Brandon G. Nguyen (barnden.dev)"

incremental: true
timezone: America/Chicago

kramdown:
  math_engine: katex

collections:
  # notes:
  #   output: true
  #   permalink: /:collection/:year/:month/:day/:title
  #   label: "notes"
  # courses:
  #   output: true
  #   permalink: /:collection/:categories/:title
  #   label: "courses"
  attractors:
    output: true
    permalink: /:collection/:title
    label: "attractors"
  misc:
    output: true
    permalink: /:collection/:title
  cards:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-minifier
  # - jekyll-paginate-v2

# Plugin Settings
jekyll-minifier:
  uglifier_args:
    harmony: true

# pagination:
#   enabled: true
#   collection: "posts"
#   per_page: 5
#   permalink: "/page/:num"
#   title: ":title | page :num"
#   sort_field: "date"
#   trail:
#     before: 2
#     after: 2
#   indexpage: "index"

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - site.zip
  - upload.sh
  - Gemfile
  - Gemfile.lock
