email: me@barnden.dev
description: >- # this means to ignore newlines until "baseurl:"
  Brandon (barnden) G. Nguyen's personal blog
baseurl: "/" # the subpath of your site, e.g. /blog
permalink: /:categories/:year/:month/:title
url: "https://barnden.dev" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: brandon-g-nguyen
github_username:  barnden

collections:
  notes:
    output: true
    permalink: /:collection/:year/:month/:day/:title
    label: "notes"
  courses:
    output: true
    permalink: /:collection/:categories/:title
    label: "courses"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-minifier
  - jekyll-mathjax-csp


# Plugin Settings
mathjax_csp:
  single_dollars: false
  output: SVG
  format: TeX
  default_csp: "default-src 'self' https://static.barnden.dev; style-src 'self' https://static.barnden.dev [CSP]; font-src 'self' https://static.barnden.dev; worker-src 'self' https://static.barnden.dev;"

jekyll-minifier:
  uglifier_args:
    harmony: true

pagination:
  enabled: true
  collection: "posts"
  per_page: 5
  permalink: "/page/:num"
  title: ":title | page :num"
  sort_field: "date"
  trail:
    before: 2
    after: 2
  indexpage: "index"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - site.zip
  - upload.sh
  - Gemfile
  - Gemfile.lock
  - csp.conf
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
